In [1]:
import time
import numpy
import pandas as pd 

In [2]:
!pip install pandas

Defaulting to user installation because normal site-packages is not writeable
You should consider upgrading via the '/usr/local/bin/python3 -m pip install --upgrade pip' command.


### why do we use numpy array over list 


1. that arrays are convenient as compared to list,  you can perform simple arithmetic operations directly, but you have to be careful about the shape and dimensionality of the array  and it also lets you visulaise the array dimensions 
2.  numpy arrays are faste than the regulr list (time complexity is an important par of our overall deployment)
3. numpy arrays takes lesser memory/ space 


In [152]:
#why do we use numpy array over list 


l = [[1],[2],[3]]
type(l)
l[0][0]+l[1][0]
l1 = [1,2,3]
l2 = [2,3,4]
print(l1+l2 , " this list got extended and he values didnt add up ")

ext= []
for i in range(3):
    ext.append(l1[i]+l2[i])
    print(l1[i]+l2[i])

ext


[1, 2, 3, 2, 3, 4]  this list got extended and he values didnt add up 
3
5
7


[3, 5, 7]

In [3]:
import numpy as np 

arrays / matrix = dimensions 

In [155]:
arr1 = np.array([1,2,3])
arr1

array([1, 2, 3])

In [156]:
arr2 = np.array([4,7,9])
arr2

array([4, 7, 9])

In [158]:
arr_add = arr1+arr2
arr_add

array([ 5,  9, 12])

In [5]:
import time 
n= 100000000
l1= range(n)
l2= range(100000000)


arr1 = np.arange(100000000)
arr2 = np.arange(100000000)

result=[]
time_start = time.time() #starting time 00:00

for i in range(n): 
    result.append(l1[i]+ l2[i])
#result = [l1[i]+ l2[i] for i range(n)] 
print("the time taken by lists for addition oopeartion ", (time.time()-time_start)*100)


the time taken by lists for addition oopeartion  4128.27525138855


In [18]:
import time 
n= 100000000
l1= range(n)
l2= range(100000000)

In [6]:
arr1 = np.arange(100000000)
arr2 = np.arange(100000000)


In [8]:
s= time.time()

arr= arr1+arr2
print("time taken", (time.time()-s)*100)

time taken 51.09450817108154


In [25]:
result=[]
time_start = time.time()

for i in range(n): 
    result.append(l1[i]+ l2[i])
#result = [l1[i]+ l2[i] for i range(n)]
print("the time taken by istes for addition oopeartion ", (time.time()-time_start)*100)


the time taken by istes for addition oopeartion  4006.7658185958862


In [9]:
time_start

1675528641.7058787

In [10]:
import sys

In [11]:
sys.getsizeof(1) ,sys.getsizeof(12) ,

(28, 28)

In [16]:
sys.getsizeof('')

49

In [18]:
sys.getsizeof(1.12341)

24

In [32]:
l1 = range(1,1000) # (start, stop , step )
l1[0], l1[1] , l1[2]

(1, 2, 3)

1
5
9


In [35]:
l1[0]

1

In [29]:
arr1 = np.arange(1,1000) # array+range

In [30]:
arr1

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103, 104,
       105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117,
       118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130,
       131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143,
       144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156,
       157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169,
       170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 18

In [55]:
arr1[0]# this is the access of first value of my array 

1

In [34]:
arr1.size , arr1.itemsize

(999, 8)

In [28]:
len(l1)

100000000

In [33]:
print(sys.getsizeof(999)*len(l1), "bytes", 'this is the size of list ')

27972 bytes this is the size of list 


In [35]:
print((arr1.size)*arr1.itemsize, "bytes")

7992 bytes


### ARRAY CREATION 

In [58]:
#ITERaBLE oBJECT 
tup= (1)
type(tup)

int

In [63]:
tup= (1,2,3,4,5)
type(tup)
tup[-1]

5

In [60]:
l = [1]

In [61]:
l.append(2)

In [37]:
l= [1,2,3,10,12,34,56]
l

[1, 2, 3, 10, 12, 34, 56]

In [64]:
array_f_list = np.array([1,2,3,4])

In [36]:
np.array([1,2,3,10,12,34,56])

array([ 1,  2,  3, 10, 12, 34, 56])

In [40]:
l = [[5,6,7,8] ]
array_f_list = np.array(l)

In [42]:
l

[[5, 6, 7, 8]]

In [43]:
array_f_list

array([[5, 6, 7, 8]])

In [41]:

array_f_list.ndim

2

In [59]:
l = ['', 'shikhachaudhary']
l

['', 'shikhachaudhary']

In [60]:
arr_ = np.array(l)
arr_.dtype

dtype('<U15')

In [52]:
tup= (1,2,3,4,5)
type(tup)
#tup[-1]

numpy.ndarray

In [47]:
array_f_tuple = np.array(tup)
array_f_tuple
array_f_tuple.dtype

dtype('int64')

In [77]:
array_f_list.ndim

1

In [48]:
s= {1,2,3,4,5,6,7,8,9,10}

In [49]:
array_set = np.array(s)
array_set

array({1, 2, 3, 4, 5, 6, 7, 8, 9, 10}, dtype=object)

In [50]:
array_set.ndim

0

In [51]:
array_set = np.array(list(s))
array_set

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [91]:
s= 'shikha '
s.upper()

'SHIKHA '

In [87]:
ar = np.array([1,'shikha '])

In [88]:
ar

array(['1', 'shikha '], dtype='<U21')

In [89]:
ar.dtype

dtype('<U21')

In [92]:
type(ar)

numpy.ndarray

In [61]:
l2 = [[1.0,2.0,3.0], [5.0,6.0,7.0]] 

In [62]:
l2

[[1.0, 2.0, 3.0], [5.0, 6.0, 7.0]]

In [63]:
arr2d = np.array(l2)

In [69]:
arr2d

array([[1., 2., 3.],
       [5., 6., 7.]])

In [65]:
arr2d.ndim

2

In [66]:
arr2d.dtype,arr2d.itemsize

(dtype('float64'), 8)

In [71]:
ar_mix = np.array([1,'shikha ',2.3])

In [72]:
ar_mix.dtype


dtype('<U32')

In [75]:
ar_mix.itemsize

128

In [76]:
array_f_list.itemsize

8

In [77]:
array_set.itemsize

8

In [74]:
array_f_list

array([[5, 6, 7, 8]])

In [78]:
list3d = [[[2,8,5], [3,6,9]], [[2,5,4], [5,6,7]]]
list3d


[[[2, 8, 5], [3, 6, 9]], [[2, 5, 4], [5, 6, 7]]]

In [79]:
arr3d = np.array([[ [2,8,5], [3,6,9]], [[2,5,4], [5,6,7]]])

In [110]:
arr3d

array([[[2, 8, 5],
        [3, 6, 9]],

       [[2, 5, 4],
        [5, 6, 7]]])

In [113]:
arr3d.ndim


3

In [80]:
l4d = [[[[5,4,10]]]]

In [81]:
l4d

[[[[5, 4, 10]]]]

In [82]:
arr4d = np.array(l4d)

In [83]:
arr4d.ndim

4

In [125]:
arr4d[0][0][0][2]

10

In [84]:
ar_3d = np.array([1,2,3,4] , ndmin=3) 

np.array( [1,2,3,4,5,6] , ndmin= 4)
# ndmin is an argument #there is a difference between ndim and ndmin

array([[[[1, 2, 3, 4, 5, 6]]]])

In [85]:
ar_3d

array([[[1, 2, 3, 4]]])

In [86]:
ar_3d.ndim  # attribute/it is acting like object 


3

In [87]:
ar_5d = np.array([1,2,3,4] , ndmin=5 , dtype = float)

#def me_func(x= 10):
#    print(x, "HEY" )


In [88]:
ar_5d


array([[[[[1., 2., 3., 4.]]]]])

In [134]:
ar_5d.ndim

5

In [136]:
ar_d = np.array([1,2,3,4] , dtype=float)

In [137]:
ar_d

array([1., 2., 3., 4.])

In [89]:
ar_dc = np.array([[1,2,3,4], [5,6,7,8]] , dtype=complex)

In [90]:
ar_dc

array([[1.+0.j, 2.+0.j, 3.+0.j, 4.+0.j],
       [5.+0.j, 6.+0.j, 7.+0.j, 8.+0.j]])

In [91]:
ar_i = np.array([[1.0,2,4.3,4], [5,6,7,8]], dtype = int)

In [92]:
ar_i

array([[1, 2, 4, 4],
       [5, 6, 7, 8]])

In [93]:
d = {1: "one" , 2: "two"}

In [94]:
d

{1: 'one', 2: 'two'}

In [95]:
np.array(d).ndim

0

In [100]:
type(list(d.keys()))


list

In [103]:
keys_dic = d.keys()
list_keys = list(keys_dic)
np.array(d.keys())

array(dict_keys([1, 2]), dtype=object)

In [105]:
np.array(list(d.keys())).ndim

1

In [106]:
ar= np.arange(100,30,-3) # start,stop,step
ar

array([100,  97,  94,  91,  88,  85,  82,  79,  76,  73,  70,  67,  64,
        61,  58,  55,  52,  49,  46,  43,  40,  37,  34,  31])

In [1]:
import random 
import numpy as np 

In [3]:
l1 = [12, 23, 45, 56 ]
l1

[12, 23, 45, 56]

In [6]:
random.choice(l1)


56

In [10]:
random.random()

0.8244962942791294

In [22]:
np.random.random((2,2))

array([[0.24869047, 0.72776249],
       [0.51456206, 0.99779377]])

In [15]:
np.random.randint(100)

81

In [16]:
np.random.rand(10)

array([0.561548  , 0.41567333, 0.93993523, 0.26107965, 0.81685681,
       0.22427507, 0.84869085, 0.76521576, 0.7237637 , 0.45846271])

In [20]:
np.random.randint(10, size=(3,3))

array([[8, 8, 6],
       [7, 1, 0],
       [0, 5, 2]])

In [23]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [25]:
np.ones((2,2), dtype = int)

array([[1, 1],
       [1, 1]])

In [32]:
ar =np.ones((2,3), dtype = int)
ar

array([[1, 1, 1],
       [1, 1, 1]])

In [33]:
ar.size

6

In [34]:
ar.shape

(2, 3)

In [36]:
np.identity(5, dtype = int)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [37]:
import numpy.matlib

In [39]:
a= numpy.matlib.identity(5)
a

matrix([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [40]:
np.linspace(10,20, 5)

array([10. , 12.5, 15. , 17.5, 20. ])

In [41]:
np.linspace(10,20, 5, endpoint= False)

array([10., 12., 14., 16., 18.])

In [42]:
x = np.array([[1,2,3,4], [5,6,7,8]] )

In [43]:
x

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [50]:
x[1][0] , x.shape , x.size

(5, (2, 4), 8)

In [55]:
rx=x.reshape(8,1)
rx

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8]])

In [59]:
x1 = np.array([11,12,13,14,15,14,67,34,12,34,56,78])
x1.size, x1.shape

(12, (12,))

In [60]:
x1.reshape(4,3)

array([[11, 12, 13],
       [14, 15, 14],
       [67, 34, 12],
       [34, 56, 78]])

In [61]:
x1.reshape(2,2,3)

array([[[11, 12, 13],
        [14, 15, 14]],

       [[67, 34, 12],
        [34, 56, 78]]])

In [62]:
y = np.arange(10)
y

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [63]:
y = np.arange(10).reshape(2,5)

In [64]:
y

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [65]:
y.reshape(1,-1)

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [66]:
y.reshape(-1,1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [67]:
y.reshape(-1,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [69]:
y.reshape(5,-1)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [70]:
y.reshape(5,2,-1)

array([[[0],
        [1]],

       [[2],
        [3]],

       [[4],
        [5]],

       [[6],
        [7]],

       [[8],
        [9]]])

In [71]:
y

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [72]:
x1

array([11, 12, 13, 14, 15, 14, 67, 34, 12, 34, 56, 78])

In [73]:
x3d = x1.reshape(3,2,2)

In [74]:
x3d

array([[[11, 12],
        [13, 14]],

       [[15, 14],
        [67, 34]],

       [[12, 34],
        [56, 78]]])

In [79]:
x3d[0][0][1]

12

In [78]:
x3d[2][1][1]

78

In [82]:
for i in x3d : 
    for j in i : 
        for k in j : 
            print(k)

11
12
13
14
15
14
67
34
12
34
56
78


In [83]:
x3d

array([[[11, 12],
        [13, 14]],

       [[15, 14],
        [67, 34]],

       [[12, 34],
        [56, 78]]])

In [84]:
x3d.flatten()

array([11, 12, 13, 14, 15, 14, 67, 34, 12, 34, 56, 78])

In [86]:
x3d

array([[[11, 12],
        [13, 14]],

       [[15, 14],
        [67, 34]],

       [[12, 34],
        [56, 78]]])

In [89]:
v = x3d.ravel()

In [90]:
for i in x3d.ravel() : 
    print(i)

11
12
13
14
15
14
67
34
12
34
56
78


In [91]:
x3d = np.array( [[ [1,2,3,4] , [5,6,7,8]], [[9,10,11,12] , [13,14,15,16]]])

In [92]:
x3d

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8]],

       [[ 9, 10, 11, 12],
        [13, 14, 15, 16]]])

In [95]:
#x3d[0][1][2]
x3d[1,0,2]

11

In [96]:
x3d[1,1,0] , x3d[1,1,1]

(13, 14)

In [97]:
x = np.array([[1,2,3,4] , [5,6,7,8]])

In [98]:
x

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [99]:
x.sum()

36

In [102]:
x.min() , x.max() , x.mean(), x.std()

(1, 8, 4.5, 2.29128784747792)

In [103]:
x

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [105]:
x.sum(axis=1) #row wise

array([10, 26])

In [106]:
x.sum(axis=0) #column wise

array([ 6,  8, 10, 12])

In [107]:
np.eye(4,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [108]:
np.eye(4,5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.]])

In [109]:
np.eye(4,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [112]:
np.eye(4,4 , k = -1)

array([[0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [114]:
np.eye(4,4 , k = 2)

array([[0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [119]:
x = np.array([1,2,3,4,5,6])# (start, stop , step )
np.flip(x)

array([6, 5, 4, 3, 2, 1])

In [116]:
x[:]

array([1, 2, 3, 4, 5, 6])

In [122]:
x[0::3]

array([1, 4])

In [123]:
x[2:]

array([3, 4, 5, 6])

In [124]:
x[:4]

array([1, 2, 3, 4])

In [126]:
ar2 = np.arange(20) 
ar2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [128]:
ar2[-1], ar2[-2]

(19, 18)

In [130]:
ar2[-4: : -1]

array([16, 15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

In [131]:
ar3 = np.arange(36).reshape(6,6)
ar3

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [132]:
ar3[0,3:5]

array([3, 4])

In [133]:
ar3[0:2,3:5]

array([[ 3,  4],
       [ 9, 10]])

In [134]:
ar3

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [135]:
ar3[4:,4:]

array([[28, 29],
       [34, 35]])

In [136]:
ar3[: , 2]

array([ 2,  8, 14, 20, 26, 32])

In [137]:
arr4 = np.arange(45).reshape(3,3,5)

In [138]:
arr4

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]],

       [[15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]],

       [[30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44]]])

In [150]:
arr4[0:2,1:,2::2]

array([[[ 7,  9],
        [12, 14]],

       [[22, 24],
        [27, 29]]])

In [139]:
arr4[0]

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [141]:
arr4[-1]

array([[30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44]])

In [143]:
arr4[0,0]

array([0, 1, 2, 3, 4])

In [144]:
arr4[0]

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [146]:
arr4[0,0,-1]

4

In [147]:
arr4[0,1,2:]

array([7, 8, 9])

In [148]:
arr4[0,0:2,2:]

array([[2, 3, 4],
       [7, 8, 9]])

In [172]:
d= np.array([ [0.1,0.2,0.3], [100,110,101] , [220,202,200] , [310,340,330] ],dtype=int)

In [173]:
d

array([[  0,   0,   0],
       [100, 110, 101],
       [220, 202, 200],
       [310, 340, 330]])

In [174]:
d.T

array([[  0, 100, 220, 310],
       [  0, 110, 202, 340],
       [  0, 101, 200, 330]])

In [175]:
np.transpose(d)

array([[  0, 100, 220, 310],
       [  0, 110, 202, 340],
       [  0, 101, 200, 330]])

In [166]:
#np.logspace()

In [167]:
d

array([[1.00e-01, 2.00e-01, 3.00e-01],
       [1.00e+02, 1.10e+02, 1.01e+02],
       [2.20e+02, 2.02e+02, 2.00e+02],
       [3.10e+02, 3.40e+02, 3.30e+02]])

In [168]:
d[:,-1]

array([3.00e-01, 1.01e+02, 2.00e+02, 3.30e+02])

In [169]:
d.max()

340.0

In [178]:
d.max(axis=1)

array([  0, 110, 220, 340])

In [177]:
d

array([[  0,   0,   0],
       [100, 110, 101],
       [220, 202, 200],
       [310, 340, 330]])